### ISSUE TITLE
请求支持lspatch

### ISSUE THREAD

**Issue by sche11** [Xposed-Modules-Repo/com.houvven.guise#11]
在lspatch上先显示未激活，应用设置选项变灰，不可开关。

**Comment by Houvven** [comment]
会增加取消对激活状态的检测配置项

**Comment by sche11** [comment]
开启后日志显示`loadPackage: is not enable, skip.`测试应用为钱迹，微信。
安卓10，lspatch最新0.5.1 (368)，本地模式。

**Comment by sche11** [comment]
> 会增加取消对激活状态的检测配置项

开启后日志显示`loadPackage: is not enable, skip.`测试应用为钱迹，微信。
安卓10，lspatch最新0.5.1 (368)，本地模式。

**Comment by Houvven** [comment]
如果免root加载配置需要使用contentprovide ，则需要保持模块在后台运行。这不是一个稳定的方案，暂时不会考虑。

**Comment by Houvven** [comment]
已完成

**Comment by xymeng16** [comment]
请问是否还存在这个问题？目前我仍然会遇到，安卓13，coloros，guise模块改机型，任何应用均not enable
