### ISSUE TITLE
Translate request

### ISSUE THREAD

**Issue by Mahantor** [Xposed-Modules-Repo/com.houvven.guise#12]
Please add english language to app

**Comment by Houvven** [comment]
> Please add english language to app
> 
Hello, the new version has included English, Japanese and Arabic translations

**Comment by Mahantor** [comment]
Where can I download the new version? The release section is empty

**Comment by Houvven** [comment]
> Where can I download the new version? The release section is empty

Now is ok.

**Comment by Mahantor** [comment]
The setting section is not completely translated, please complete the translation of this section as well
![Screenshot_2023-02-14-14-18-26-207_com.houvven.guise.jpg](https://user-images.githubusercontent.com/91434001/218715337-6c0004a9-4ea2-4add-9afd-14cf2130dd70.jpg)
