### ISSUE TITLE
有关qq

### ISSUE THREAD

**Issue by yhzcake** [Xposed-Modules-Repo/com.houvven.guise#31]
新版qq支持手机平板同时登录,但是我不太清除判断依据
不知道有没有办法改成能通过pad协议登录

**Comment by sch-lda** [comment]
如果你使用了QAuxiliary模块，可以直接在实验性功能了找到强制平板模式

**Comment by yhzcake** [comment]
> 如果你使用了QAuxiliary模块，可以直接在实验性功能了找到强制平板模式

十分感谢，我成功的在我的手机和wsa上同时登录了qq

wsa不支持平行视界，感觉好丑，请问有模块可以使用吗
