### ISSUE TITLE
米家登录界面，强制截屏失效

### ISSUE THREAD

**Issue by VictorChow** [Xposed-Modules-Repo/com.houvven.guise#5]
### 1. 现象
Guise勾选米家作用域，配置米家强制允许截图，在米家登录界面使用系统截图，toast提示“该应用不允许屏幕截图”
### 2. 设备信息
小米13，MIUI 14.0.13，Android 13
### 3. 应用信息
Guise：1.0.7
米家：8.0.709
截屏：RELEASE-1.4.29-11071135

**Comment by woai66** [comment]
安卓13的原因
